name-template: "Release v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
exclude-labels:
  - "skip-changelog"
categories:
  - title: "ðŸ’¥ Breaking Changes"
    labels:
      - breaking-change
  - title: "ðŸš€ Features"
    labels:
      - feature
  - title: "ðŸ› Bug Fixes"
    labels:
      - bug
  - title: "ðŸ§° Maintenance"
    labels:
      - chore
autolabeler:
  - label: "breaking-change"
    body:
      - "/breaking change/i"
  - label: "feature"
    branch:
      - '/feature\/.+/'
    title:
      - "/feat/i"
  - label: "bug"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
  - label: "chore"
    title:
      - "/chore/"
version-resolver:
  major:
    labels:
      - "breaking-change"
  minor:
    labels:
      - "feature"
  patch:
    labels:
      - "bug"
      - "chore"
  default: patch
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
