[tool.pyright]
pythonVersion = "3.8"
include = ["scanner.py"]
reportMissingModuleSource = false     # klippy imports are always missing sources
reportPrivateLocalImportUsage = false
# TODO: Slowly remove these
strictDictionaryInference = false
reportUninitializedInstanceVariable = false
failOnWarnings = false

[tool.ruff]
target-version = "py38"
include = ["scanner.py"]
