name: Continuous integration

on:
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    name: ${{ matrix.name }} Checks
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Standard
            requirements: ./ci/standard-requirements.txt
            python-version: 3.9
            pyproject: pyproject.toml
          - name: K1
            requirements: ./ci/k1-requirements.txt
            python-version: 3.8
            pyproject: pyproject.k1.toml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - run: pip install cython wheel
      - run: pip install -r ${{ matrix.requirements }}
      - name: Linting
        uses: astral-sh/ruff-action@v1
        continue-on-error: true # let's remove this once ruff has been implemented in scanner.py
      - name: Type check
        run: |
          pip install basedpyright && \
          basedpyright --project ${{ matrix.pyproject }}
