name: Continuous integration

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"
      - run: pip install -r requirements.txt
      - name: Linting
        uses: astral-sh/ruff-action@v1
        continue-on-error: true # let's remove this once ruff has been implemented in scanner.py
      - name: Type check
        run: pip install basedpyright && basedpyright
